services:
  echo-server:
    container_name: "echo-server"
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - $PWD:/go/src/target
    env_file:
      - ./.env
      

  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: ktaxes
  #   ports:
  #     - '5432:5432'
