services:
  echo-server:
    container_name: "echo-server"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/go/src/target
      

  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: ktaxes
  #   ports:
  #     - '5432:5432'
